BurgerProject/Areas/Admin/Controllers/ExtraController.cs
using BurgerProject.Data.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BurgerProject.Data.Entities;
using BurgerProject.Data;
using BurgerProject.Data.Entities.Concrete;
using BurgerProject.Areas.Admin.Models;
using BurgerProject.Migrations;

namespace BurgerProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ExtraController : Controller
    {
        private readonly BurgerDbContext _burgerDbContext;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ExtraController(BurgerDbContext burgerDbContext, IWebHostEnvironment hostingEnvironment)
        {
            _burgerDbContext = burgerDbContext;
            _hostingEnvironment = hostingEnvironment;
        }


        public async Task<IActionResult> Index()
        {

            return View(await _burgerDbContext.Extras.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var extra = await _burgerDbContext.Extras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (extra == null)
            {
                return NotFound();
            }

            return View(extra);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        
        public async Task<IActionResult> Create(ExtraViewModel extraViewModel, Extra extra)
        {
            if (extraViewModel.LogoFile != null)
            {

                var extent = Path.GetExtension(extraViewModel.LogoFile.FileName);
                var dumyName = Guid.NewGuid().ToString();
                dumyName += extent;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", dumyName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await extraViewModel.LogoFile.CopyToAsync(stream);
                }
                extra.LogoFile = dumyName;


            }
            else
            {
                extra.LogoFile = null;
            }
            if (!ModelState.IsValid)
            {
               
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine(error.ErrorMessage); 
                    }
                }
                return View(extraViewModel);
            }
            extra.ExtraName = extraViewModel.ExtraName;
            extra.ExtraPrice = extraViewModel.ExtraPrice;
            extra.CreatedDate = DateTime.Now;
            _burgerDbContext.Add(extra);
            await _burgerDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id, ExtraViewModel extraViewModel)
        {
            if (id == null)
            {
                return NotFound();
            }

            var extra = await _burgerDbContext.Extras.FirstOrDefaultAsync(m => m.Id == id);
            if (extra == null)
            {
                return NotFound();
            }
            extraViewModel.ExtraName = extra.ExtraName;
            extraViewModel.ExtraPrice = extra.ExtraPrice;
            extraViewModel.LogoFile = (IFormFile?)TempData["LogoFile"];
            ViewBag.LogoFile = extra.LogoFile;
            TempData["Id"] = id;
            return View(extraViewModel);
        }
        [HttpPost]
    
        public async Task<IActionResult> Edit(int id, ExtraViewModel extraViewModel)
        {
            var oldExtra = await _burgerDbContext.Extras.FindAsync(id);
            if (id != (int)TempData["Id"])
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
                return View(extraViewModel);
            }
            else
            {
                try
                {

                    if (oldExtra == null)
                    {
                        return NotFound();
                    }

                    if (!string.IsNullOrEmpty(oldExtra.ExtraName))
                    {
                        oldExtra.ExtraName = extraViewModel.ExtraName;
                    }

                    if (extraViewModel.ExtraPrice != null)
                    {
                        oldExtra.ExtraPrice = extraViewModel.ExtraPrice;
                    }

                   

                    if (extraViewModel.LogoFile != null)
                    {
                        var extension = Path.GetExtension(extraViewModel.LogoFile.FileName);
                        var dummyName = Guid.NewGuid().ToString() + extension;
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", dummyName);
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await extraViewModel.LogoFile.CopyToAsync(stream);
                        }
                        oldExtra.LogoFile = dummyName; // Sadece dosya adını sakla
                    }
                    else
                    {
                        oldExtra.LogoFile = oldExtra.LogoFile;
                    }



                    oldExtra.UpdatedDate = DateTime.Now;
                    _burgerDbContext.Update(oldExtra);
                    await _burgerDbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExtraExists((int)TempData["Id"]))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
        }
        private bool ExtraExists(int id)
        {
            return _burgerDbContext.Extras.Any(e => e.Id == id);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var extra = await _burgerDbContext.Extras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (extra == null)
            {
                return NotFound();
            }

            return View(extra);
        }
        [HttpPost, ActionName("Delete")]
        
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var extra = await _burgerDbContext.Extras.FindAsync(id);
            if (extra != null)
            {
                _burgerDbContext.Extras.Remove(extra);
            }
            DeleteLogoFile(extra);
            await _burgerDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public void DeleteLogoFile(Extra extra)
        {
            if (extra.LogoFile != null){
                var resmiKullananBaskaVarMi = _burgerDbContext.Extras.Any(u => u.LogoFile == extra.LogoFile && u.Id != extra.Id);
                if (!resmiKullananBaskaVarMi)
                {
                    string webRootPath = _hostingEnvironment.WebRootPath;
                    //string deleteLogo = Path.Combine(webRootPath + extra.LogoFile);

                    var deleteLogo = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", extra.LogoFile);

                    System.IO.File.Delete(deleteLogo);
                }
            }
           
        }



    }
}

BurgerProject/Controllers/MenuController.cs
using BurgerProject.Data.Context;
using BurgerProject.Data.Entities.Concrete;
using BurgerProject.Data.Enums;
using BurgerProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BurgerProject.Controllers
{
    
    public class MenuController : Controller
    {

        private readonly BurgerDbContext _context;
        private UserManager<AppUser> _userManager;

        public MenuController(BurgerDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var menuItems = _context.Menus.ToList();
            var extraItems = _context.Extras.ToList();
            var viewModel = new MenuViewModel
            {
                Menus = menuItems,
                Extras = extraItems
            };
            return View(viewModel);
        }




        [HttpPost]
        public IActionResult CreateOrder(OrderViewModel orderViewModel, List<int> selectedExtras)
        {
            if (!User.Identity.IsAuthenticated)
            {
                ViewBag.Error = "Sipariş vermek için giriş yapmalısınız.";
                return RedirectToAction("Index"); 
            }
            var userId = Convert.ToInt32(_userManager.GetUserId(HttpContext.User)); //sisteme login olanın id'sini verir.

        


            if (ModelState.IsValid)
            {
                // Seçilen ekstra malzemelerin listesini oluştur
                var selectedExtraList = new List<Extra>();
                if (selectedExtras != null && selectedExtras.Any())
                {
                    foreach (var extraId in selectedExtras)
                    {
                        var extra = _context.Extras.Find(extraId);
                        if (extra != null)
                        {
                            selectedExtraList.Add(extra);
                        }
                    }
                }

                // Yeni bir sipariş oluştur
                Order order = new Order
                {
                    OrderSize = orderViewModel.OrderSize,
                    MenuId = orderViewModel.MenuId,
                    Piece = orderViewModel.Piece,
                    AppUserId = userId,
                    CreatedDate = DateTime.Now,
                    Extras = selectedExtraList // Seçilen ekstra malzemeleri ekle
                };

                // Yeni siparişi kaydet
                _context.Orders.Add(order);
                _context.SaveChanges();

                
            }

            else if (!ModelState.IsValid) 
            {
                TempData["Message"] = "Sipariş vermek için gerekli yerleri doldurmalısınız.";
                return RedirectToAction("Index");
            }

            TempData["Message"] = "Siparişiniz başarıyla oluşturulmuştur, siparişlerim bölümünden kontrol edebilirsiniz.";
            return RedirectToAction("Index");

        }










    }
}

BurgerProject/Controllers/OrderController.cs
using BurgerProject.Data.Context;
using BurgerProject.Data.Entities.Concrete;
using BurgerProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BurgerProject.Controllers
{
    public class OrderController : Controller
    {
        private readonly BurgerDbContext _context;
        private UserManager<AppUser> _userManager;

        public OrderController(BurgerDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var userId = Convert.ToInt32(_userManager.GetUserId(HttpContext.User)); // Sisteme login olanın ID'sini verir.
            List<double> totalPrice = FiyatHesapla(userId);
            var userOrders = _context.Orders
                .Include(o => o.Extras)
                .Include(o => o.Menu)
                .Where(o => o.AppUserId == userId)
                .Select(o => new OrderListViewModel
                {
                    Id = o.Id,
                    OrderSize = o.OrderSize,
                    Piece = o.Piece,
                    MenuName = o.Menu.MenuName,
                    AppUserId = o.AppUserId,
                    Extras = o.Extras.ToList(),
                    MenuId = o.MenuId,
                    Menu = o.Menu
                })
                .ToList();

            for (int i = 0; i < totalPrice.Count; i++)
            {
                userOrders[i].TotalPrice = totalPrice[i];
            }
            return View(userOrders);
        }
        public IActionResult Delete(int? id) 
        { 
            if (id == null)
            {
                return NotFound();
            }

            var order = _context.Orders
                .FirstOrDefault(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            else
            
            {
                _context.Orders.Remove(order);
                _context.SaveChanges();

            }
            

            return RedirectToAction(nameof(Index)); 
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var order = _context.Orders
                .Include(o => o.Extras)
                .Include(o => o.Menu)
                .FirstOrDefault(o => o.Id == id);

            if (order == null)
            {
                return NotFound();
            }

            var viewModel = new OrderListViewModel
            {
                Id = order.Id,
                OrderSize = order.OrderSize,
                Piece = order.Piece,
                MenuName = order.Menu.MenuName,
                AppUserId = order.AppUserId,
                Extras = order.Extras.ToList(),
                MenuId = order.MenuId,
                Menu = order.Menu,
                TotalExtraPrice = order.Extras.Sum(e => e.ExtraPrice),
                MenuPrice = order.Menu.MenuPrice
            };

            viewModel.TotalPrice = CalculateTotalPrice(viewModel);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(OrderListViewModel model)
        {
            if (ModelState.IsValid)
            {
                var order = _context.Orders
                    .Include(o => o.Extras)
                    .Include(o => o.Menu)
                    .FirstOrDefault(o => o.Id == model.Id);

                if (order == null)
                {
                    return NotFound();
                }

                order.OrderSize = model.OrderSize;
                order.Piece = model.Piece;
                

                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        private double CalculateTotalPrice(OrderListViewModel order)
        {
            double totalPrice = 0;
            if (order.OrderSize == Data.Enums.OrderSize.Kucuk)
            {
                totalPrice = order.Piece * order.Menu.MenuPrice + order.TotalExtraPrice;
            }
            else if (order.OrderSize == Data.Enums.OrderSize.Orta)
            {
                double orta = 1.3;
                totalPrice = (order.Piece * order.Menu.MenuPrice) * orta + order.TotalExtraPrice;
            }
            else
            {
                double buyuk = 1.5;
                totalPrice = (order.Piece * order.Menu.MenuPrice) * buyuk + order.TotalExtraPrice;
            }
            return totalPrice;
        }

        public List<double> FiyatHesapla(int userId)
        {
            List<double> totalPriceList = new List<double>();

            List<OrderListViewModel> orderList = _context.Orders
                .Include(o => o.Extras)
                .Include(o => o.Menu)
                .Where(o => o.AppUserId == userId)
                .Select(order => new OrderListViewModel
            {
                TotalExtraPrice = order.Extras.Sum(e => e.ExtraPrice),
                OrderSize = order.OrderSize,
                Piece = order.Piece,
                Menu = order.Menu,
                MenuPrice = order.Menu.MenuPrice

            }).ToList();
            var toplamfiyat = 0;

            foreach(var order in orderList)
            {
                if(order.OrderSize == Data.Enums.OrderSize.Kucuk)
                {
                    order.TotalPrice = order.Piece * order.Menu.MenuPrice + order.TotalExtraPrice;
                }
                else if (order.OrderSize == Data.Enums.OrderSize.Orta)
                {
                    double orta = 1.3;
                    order.TotalPrice = (order.Piece * order.Menu.MenuPrice) * orta + order.TotalExtraPrice;

                }
                else
                {
                    double buyuk = 1.5;
                    order.TotalPrice = (order.Piece * order.Menu.MenuPrice) * buyuk + order.TotalExtraPrice;
                }
            };
            foreach (var order in orderList)
            {
                totalPriceList.Add(order.TotalPrice);
            }

            return totalPriceList;
        }

    }
}

BurgerProject/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>BurgerGurme-Admin Paneli</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.png">
    <link rel="stylesheet" href="~/admin/vendor/owl-carousel/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/admin/vendor/owl-carousel/css/owl.theme.default.min.css">
    <link href="~/admin/vendor/jqvmap/css/jqvmap.min.css" rel="stylesheet">
    <link href="~/admin/css/style.css" rel="stylesheet">



</head>

<body>


    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <a asp-controller="Home" asp-action="Index" class="brand-logo">
                <img class="logo-abbr" src="~/admin/images/admin2.png" alt="">
                <img class="logo-compact" src="~/admin/images/logo-text2.png" alt="">
                <img class="brand-title" src="~/admin/images/logo-text2.png" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>

                
            </div>

          
            
        </div>
       
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                    </div>
                </nav>
                <a asp-controller="Account" asp-action="Logout">
                    <strong>Siteye Dönüş</strong>
                </a>
            </div>
        </div>
        
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->
        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="quixnav">
            <div class="quixnav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label first">İşlemler</li>


                    <li>
                        <a asp-controller="Home" asp-action="Index" aria-expanded="false">
                            <i class="icon icon-layout-25"></i><span class="nav-text">Anasayfa</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Menu" asp-action="Index" aria-expanded="false">
                            <i class="icon icon-layout-25"></i><span class="nav-text">Burger Menüleri</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Extra" asp-action="Index" aria-expanded="false">
                            <i class="icon icon-layout-25"></i><span class="nav-text">Extra Malzemeler</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Customer" asp-action="Index" aria-expanded="false">
                            <i class="icon icon-layout-25"></i><span class="nav-text">Müşteriler</span>
                        </a>
                    </li>
                    
                     <li>
                        <a asp-controller="Order" asp-action="Index" aria-expanded="false">
                            <i class="icon icon-layout-25"></i><span class="nav-text">Siparişler</span>
                        </a>
                    </li>
                </ul>
            </div>


        </div>


       <div class="content-body">
			<div class="container-fluid">
				@RenderBody()
			</div>
		</div>



        <!-- Required vendors -->
        <script src="~/admin//vendor/global/global.min.js"></script>
        <script src="~/admin//js/quixnav-init.js"></script>
        <script src="~/admin//js/custom.min.js"></script>


        <!-- Vectormap -->
        <script src="~/admin/vendor/raphael/raphael.min.js"></script>
        <script src="~/admin/vendor/morris/morris.min.js"></script>


        <script src="~/admin/vendor/circle-progress/circle-progress.min.js"></script>
        <script src="~/admin/vendor/chart.js/Chart.bundle.min.js"></script>

        <script src="~/admin/vendor/gaugeJS/dist/gauge.min.js"></script>

        <!--  flot-chart js -->
        <script src="~/admin/vendor/flot/jquery.flot.js"></script>
        <script src="~/admin/vendor/flot/jquery.flot.resize.js"></script>

        <!-- Owl Carousel -->
        <script src="~/admin/vendor/owl-carousel/js/owl.carousel.min.js"></script>

        <!-- Counter Up -->
        <script src="~/admin/vendor/jqvmap/js/jquery.vmap.min.js"></script>
        <script src="~/admin/vendor/jqvmap/js/jquery.vmap.usa.js"></script>
        <script src="~/admin/vendor/jquery.counterup/jquery.counterup.min.js"></script>


        <script src="~/admin/js/dashboard/dashboard-1.js"></script>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)




</body>

</html>

BurgerProject/Areas/Admin/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Girişi</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    
    @RenderBody()

    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
</body>
</html>