BurgerProject/Controllers/MenuController.cs
using BurgerProject.Data.Context;
using BurgerProject.Data.Entities.Concrete;
using BurgerProject.Data.Enums;
using BurgerProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BurgerProject.Controllers
{
    
    public class MenuController : Controller
    {

        private readonly BurgerDbContext _context;
        private UserManager<AppUser> _userManager;

        public MenuController(BurgerDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var menuItems = _context.Menus.ToList();
            var extraItems = _context.Extras.ToList();
            var viewModel = new MenuViewModel
            {
                Menus = menuItems,
                Extras = extraItems
            };
            return View(viewModel);
        }




        [HttpPost]
        public IActionResult CreateOrder(OrderViewModel orderViewModel, List<int> selectedExtras)
        {
            if (!User.Identity.IsAuthenticated)
            {
                ViewBag.Error = "Sipariş vermek için giriş yapmalısınız.";
                return RedirectToAction("Index"); 
            }
            var userId = Convert.ToInt32(_userManager.GetUserId(HttpContext.User)); //sisteme login olanın id'sini verir.

        


            if (ModelState.IsValid)
            {
                // Seçilen ekstra malzemelerin listesini oluştur
                var selectedExtraList = new List<Extra>();
                if (selectedExtras != null && selectedExtras.Any())
                {
                    foreach (var extraId in selectedExtras)
                    {
                        var extra = _context.Extras.Find(extraId);
                        if (extra != null)
                        {
                            selectedExtraList.Add(extra);
                        }
                    }
                }

                // Yeni bir sipariş oluştur
                Order order = new Order
                {
                    OrderSize = orderViewModel.OrderSize,
                    MenuId = orderViewModel.MenuId,
                    Piece = orderViewModel.Piece,
                    AppUserId = userId,
                    CreatedDate = DateTime.Now,
                    Extras = selectedExtraList // Seçilen ekstra malzemeleri ekle
                };

                // Yeni siparişi kaydet
                _context.Orders.Add(order);
                _context.SaveChanges();

                
            }

            else if (!ModelState.IsValid) 
            {
                TempData["Message"] = "Sipariş vermek için gerekli yerleri doldurmalısınız.";
                return RedirectToAction("Index");
            }

            TempData["Message"] = "Siparişiniz başarıyla oluşturulmuştur, siparişlerim bölümünden kontrol edebilirsiniz.";
            return RedirectToAction("Index");

        }










    }
}

BurgerProject/Controllers/OrderController.cs
using BurgerProject.Data.Context;
using BurgerProject.Data.Entities.Concrete;
using BurgerProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BurgerProject.Controllers
{
    public class OrderController : Controller
    {
        private readonly BurgerDbContext _context;
        private UserManager<AppUser> _userManager;

        public OrderController(BurgerDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var userId = Convert.ToInt32(_userManager.GetUserId(HttpContext.User)); // Sisteme login olanın ID'sini verir.
            List<double> totalPrice = FiyatHesapla(userId);
            var userOrders = _context.Orders
                .Include(o => o.Extras)
                .Include(o => o.Menu)
                .Where(o => o.AppUserId == userId)
                .Select(o => new OrderListViewModel
                {
                    Id = o.Id,
                    OrderSize = o.OrderSize,
                    Piece = o.Piece,
                    MenuName = o.Menu.MenuName,
                    AppUserId = o.AppUserId,
                    Extras = o.Extras.ToList(),
                    MenuId = o.MenuId,
                    Menu = o.Menu
                })
                .ToList();

            for (int i = 0; i < totalPrice.Count; i++)
            {
                userOrders[i].TotalPrice = totalPrice[i];
            }
            return View(userOrders);
        }
        public IActionResult Delete(int? id) 
        { 
            if (id == null)
            {
                return NotFound();
            }

            var order = _context.Orders
                .FirstOrDefault(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            else
            
            {
                _context.Orders.Remove(order);
                _context.SaveChanges();

            }
            

            return RedirectToAction(nameof(Index)); 
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var order = _context.Orders
                .Include(o => o.Extras)
                .Include(o => o.Menu)
                .FirstOrDefault(o => o.Id == id);

            if (order == null)
            {
                return NotFound();
            }

            var viewModel = new OrderListViewModel
            {
                Id = order.Id,
                OrderSize = order.OrderSize,
                Piece = order.Piece,
                MenuName = order.Menu.MenuName,
                AppUserId = order.AppUserId,
                Extras = order.Extras.ToList(),
                MenuId = order.MenuId,
                Menu = order.Menu,
                TotalExtraPrice = order.Extras.Sum(e => e.ExtraPrice),
                MenuPrice = order.Menu.MenuPrice
            };

            viewModel.TotalPrice = CalculateTotalPrice(viewModel);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(OrderListViewModel model)
        {
            if (ModelState.IsValid)
            {
                var order = _context.Orders
                    .Include(o => o.Extras)
                    .Include(o => o.Menu)
                    .FirstOrDefault(o => o.Id == model.Id);

                if (order == null)
                {
                    return NotFound();
                }

                order.OrderSize = model.OrderSize;
                order.Piece = model.Piece;
                

                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        private double CalculateTotalPrice(OrderListViewModel order)
        {
            double totalPrice = 0;
            if (order.OrderSize == Data.Enums.OrderSize.Kucuk)
            {
                totalPrice = order.Piece * order.Menu.MenuPrice + order.TotalExtraPrice;
            }
            else if (order.OrderSize == Data.Enums.OrderSize.Orta)
            {
                double orta = 1.3;
                totalPrice = (order.Piece * order.Menu.MenuPrice) * orta + order.TotalExtraPrice;
            }
            else
            {
                double buyuk = 1.5;
                totalPrice = (order.Piece * order.Menu.MenuPrice) * buyuk + order.TotalExtraPrice;
            }
            return totalPrice;
        }

        public List<double> FiyatHesapla(int userId)
        {
            List<double> totalPriceList = new List<double>();

            List<OrderListViewModel> orderList = _context.Orders
                .Include(o => o.Extras)
                .Include(o => o.Menu)
                .Where(o => o.AppUserId == userId)
                .Select(order => new OrderListViewModel
            {
                TotalExtraPrice = order.Extras.Sum(e => e.ExtraPrice),
                OrderSize = order.OrderSize,
                Piece = order.Piece,
                Menu = order.Menu,
                MenuPrice = order.Menu.MenuPrice

            }).ToList();
            var toplamfiyat = 0;

            foreach(var order in orderList)
            {
                if(order.OrderSize == Data.Enums.OrderSize.Kucuk)
                {
                    order.TotalPrice = order.Piece * order.Menu.MenuPrice + order.TotalExtraPrice;
                }
                else if (order.OrderSize == Data.Enums.OrderSize.Orta)
                {
                    double orta = 1.3;
                    order.TotalPrice = (order.Piece * order.Menu.MenuPrice) * orta + order.TotalExtraPrice;

                }
                else
                {
                    double buyuk = 1.5;
                    order.TotalPrice = (order.Piece * order.Menu.MenuPrice) * buyuk + order.TotalExtraPrice;
                }
            };
            foreach (var order in orderList)
            {
                totalPriceList.Add(order.TotalPrice);
            }

            return totalPriceList;
        }

    }
}

BurgerProject/Controllers/UserController.cs
using BurgerProject.Data.Entities.Concrete;
using BurgerProject.Models.Account;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using NuGet.Versioning;
using System.Threading.Tasks;

namespace BurgerProject.Controllers
{
	public class UserController : Controller
	{
		private readonly UserManager<AppUser> _userManager;
		private readonly RoleManager<IdentityRole<int>> _roleManager;
		private readonly SignInManager<AppUser> _signInManager;
		private readonly ICompositeViewEngine _viewEngine;
		private readonly IConfiguration _configuration;

		public UserController(UserManager<AppUser> userManager, RoleManager<IdentityRole<int>> roleManager, SignInManager<AppUser> signInManager, ICompositeViewEngine viewEngine, IConfiguration configuration)
		{
			_userManager = userManager;
			_roleManager = roleManager;
			_signInManager = signInManager;
			_viewEngine = viewEngine;
			_configuration = configuration;
		}


		[HttpGet]
		public IActionResult Register()
		{
			UserViewModel model = new UserViewModel();
			return View(model);
		}



		[HttpPost]
		public async Task<IActionResult> Register(UserViewModel model)
		{
			ModelState.Remove("UserId");

			if (!ModelState.IsValid)
				return View(model);

            
            if (model.Password != model.ConfirmPassword)
            {
                ViewBag.ErrorMessage = "Şifre ile şifre tekrarı aynı değildir.";
                return View(model);
            }

           

            var users = _userManager.Users.ToList();

			foreach (var item in users)
			{
				if (model.Email == item.Email)
				{
					ViewBag.ErrorMessage = $"{model.Email} adresi zaten kayıtlıdır";
					return View(model);
				}
			}


            var hasher = new PasswordHasher<AppUser>();

			AppUser user = new AppUser
			{
				Name = model.Name,
				Surname = model.Surname,
				Address = model.Address,
				Email = model.Email,
				EmailConfirmed = true,
				NormalizedEmail = model.Email.ToUpper(),
				PasswordHash = hasher.HashPassword(null, model.Password),
				UserName = model.Name,
				NormalizedUserName = model.Name.ToUpper()
			};



			IdentityResult result = await _userManager.CreateAsync(user);

			if (result.Succeeded)
			{
				await _userManager.AddToRoleAsync(user, "Customer");


				TempData["Message"] = "Kayıt başarılı! Giriş yapabilirsiniz.";

				return RedirectToAction(nameof(Login));
			}
			else
			{
				ViewBag.ErrorMessage = "Kayıt başarısız, lütfen tüm alanları eksiksiz ve doğru bir şekilde doldurunuz";
				return View(model);
			}


		}



		[HttpGet]
		public IActionResult Login()
		{
			LoginViewModel model = new LoginViewModel();
			return View(model);
		}

		[HttpPost]
		public IActionResult Login(LoginViewModel model)
		{
			if (!ModelState.IsValid)
			{
				ViewBag.ErrorMessage = "Lütfen kutucukları eksiksiz ve doğru doldurunuz";
				return View(model);
			}


            AppUser user = _userManager.FindByEmailAsync(model.Email).Result;

			if (user is null)
			{
				ViewBag.ErrorMessage = "Bu e-mail ile kullanıcı bulunamamıştır";
				return View(model);
			}

			Microsoft.AspNetCore.Identity.SignInResult signInResult = _signInManager.PasswordSignInAsync(user, model.Password, false, false).Result;

			if (!signInResult.Succeeded)
			{
				ViewBag.ErrorMessage = "Şifre yanlıştır.";
				return View(model);
			}

			ViewBag.LoginSuccess = user.Name;

			return RedirectToAction("Index", "Home");
		}



		public async Task<IActionResult> Logout()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}



        [HttpGet]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Edit()
        {
			var userId = _userManager.GetUserId(HttpContext.User);

			var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            
            var model = new UserViewModel
            {
                UserId = user.Id,
                Name = user.Name,
                Surname = user.Surname,
                Address = user.Address,
                Email = user.Email
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Edit(UserViewModel model, string currentPassword, string newPassword, string confirmNewPassword)
        {
			ModelState.Remove("Password");
			ModelState.Remove("ConfirmPassword");

			ModelState.Remove("newPassword");
			ModelState.Remove("currentPassword");
			ModelState.Remove("confirmNewPassword");


            if (!ModelState.IsValid)
            {
                return View(model);
            }

            
            var user = await _userManager.FindByIdAsync(model.UserId.ToString());
            if (user == null)
            {
               return View(model);
            }

            if (!string.IsNullOrEmpty(currentPassword) && !string.IsNullOrEmpty(newPassword) && !string.IsNullOrEmpty(confirmNewPassword))
            {
                if (newPassword != confirmNewPassword)
                {
                    ViewBag.ErrorMessage = "Yeni şifre ile yeni şifre tekrarı aynı değil.";
                    return View(model);
                }

                var passwordChangeResult = await _userManager.ChangePasswordAsync(user, currentPassword, newPassword);
                if (!passwordChangeResult.Succeeded)
                {
                    ViewBag.ErrorMessage = "Şifrenizde en az 1 büyük harf, en az 1 küçük harf ve en az 1 özel karakter olmalıdır";
                    return View(model);
                }
            }
            user.Name = model.Name;
            user.Surname = model.Surname;
            user.Address = model.Address;
            user.Email = model.Email;

            var result = await _userManager.UpdateAsync(user);
            if (result.Succeeded)
            {

                await _signInManager.RefreshSignInAsync(user);
                TempData["SuccessMessage"] = "Kullanıcı bilgileriniz başarıyla güncellendi.";
                return RedirectToAction("Index", "Home");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }


    }
}

BurgerProject/Views/Shared/_Layout.cshtml
@using BurgerProject.Data.Entities.Concrete
@using Microsoft.AspNetCore.Identity
@inject IHttpContextAccessor _httpContextAccessor
@inject UserManager<AppUser> _userManager
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>BurgerGurme-@ViewData["Title"]</title>
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.png">
    <link href="//fonts.googleapis.com/css2?family=Dosis:wght@300;400;500;600;800&display=swap" rel="stylesheet">

    <!-- Template CSS -->
    <link rel="stylesheet" href="~/client/css/style-starter.css">


    @* boostrapten ikon eklemek için linki yazdım *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css">

</head>
<body>

      
    <!--header-->
    <header id="site-header" class="fixed-top">
        <div class="container">
            <nav class="navbar navbar-expand-lg stroke px-0">
                <h1>
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index" >
                        <img src="~/client/images/burger.png" alt="burger logo" width="35px" /> BurgerGurme
                    </a>
                </h1>
                <button class="navbar-toggler collapsed bg-gradient" type="button" data-toggle="collapse"
                        data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
                    <span class="navbar-toggler-icon fa icon-close fa-times"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index" >Anasayfa<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item @@menu__active">
                            <a class="nav-link" asp-controller="Menu" asp-action="Index" >Menüler</a>
                        </li>
                        <li class="nav-item @@about__active">
                            <a class="nav-link" asp-controller="Home" asp-action="About" >Hakkımızda</a>
                        </li>
                        <li class="nav-item @@contact__active">
                            <a class="nav-link" asp-controller="Home" asp-action="Contact" >İletişim</a>
                        </li>


                        @if (User.Identity.IsAuthenticated)
                        {
                            var userId = _userManager.GetUserId(_httpContextAccessor.HttpContext.User);

                            var user = await _userManager.FindByIdAsync(userId);

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-person-hearts"> Hoşgeldin&nbsp; </i>  @user.Name&nbsp;   <i class="bi bi-chevron-double-down"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Order" asp-action="Index">Siparişlerim</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="User" asp-action="Edit">Profilim</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="User" asp-action="Logout">Çıkış Yap</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item boostrap-icon">
                                <a asp-controller="User" asp-action="Login">
                                    <i class="bi bi-person"></i>
                                </a>
                            </li>
                        }


                        <!-- toggle switch for light and dark theme -->
                        <li class="nav-item theme-switch-wrapper">
                            <label class="theme-switch" for="checkbox">
                                <input type="checkbox" id="checkbox">
                                <div class="mode-container">
                                    <i class="gg-sun"></i>
                                    <i class="gg-moon"></i>
                                </div>
                            </label>
                        </li>
                        <!-- //toggle switch for light and dark theme -->
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--/header-->

    
          
            @RenderBody()
   

    <!-- footer -->
    <footer class="py-5">
        <div class="container py-xl-4">
            <div class="row footer-top">
                <div class="col-lg-4 footer-grid_section_1its footer-text">
                    <h2>
                        <a class="logo text-wh" href="index.html">
                            <img src="~/client/images/burger.png" alt="burger logo" width="35px" /> BurgerGurme
                        </a>
                    </h2>
                    <!-- //logo -->
                    <p class="mt-lg-4 mt-3 mb-4 pb-lg-2">
                        Lezzetin Adresi BurgerGurme, misafirlerimizin en iyi deneyimini yaşaması için titizlikle çalışmaktadır. Sağlığınız ve güvenliğiniz bizim için önemlidir.
                    </p>
                </div>
                <div class="col-lg-4 col-sm-6 footer-grid_section_1its mt-lg-0 mt-5">
                    <div class="footer-title">
                        <h3>İletişim Bilgileri</h3>
                    </div>
                    <div class="footer-text mt-4">
                        <p>
                            <strong>Adres :</strong> BurgerGurme, Atatürk Caddesi Çankaya/Ankara
                        </p>
                        <p class="my-2"><strong>Telefon :</strong> <a href="tel:03120000000">0312 000 00 00</a></p>
                    </div>
                </div>
                <div class="col-lg-4 footer-grid_section_1its footer-text">
                    <h2>
                        <a class="logo text-wh" href="index.html">
                            <img src="~/client/images/burger.png" alt="burger logo" width="35px" /> BurgerGurme
                        </a>
                    </h2>
                    <p class="mt-lg-4 mt-3 mb-4 pb-lg-2">
                        Her lokmada mutluluk ve memnuniyet sunmayı hedefliyoruz. Kaliteli malzemeler ve özenle hazırlanan menülerimizle sizleri bekliyoruz.
                    </p>
                </div>
            </div>
        </div>
    </footer>


    <!-- //footer -->


    <!-- copyright -->
    <div class="cpy-right text-center py-4">
        <p>© 2024 BurgerGurme. Tüm hakları saklıdır | Design by 
            <a href="https://www.linkedin.com/in/burak-gonca/">Burak Gonca</a> |
            <a href="https://www.linkedin.com/in/benguurgendemir/">Bengü Ürgen Demir</a> |
            <a href="https://www.linkedin.com/in/ilgin-deniz-ayaz/">Ilgın Deniz Ayaz</a>

        </p>
    </div>


    <!-- //copyright -->
    <!-- move top -->
    <button onclick="topFunction()" id="movetop" title="Go to top">
        <span class="fa fa-level-up" aria-hidden="true"></span>
    </button>
    <script>
        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("movetop").style.display = "block";
            } else {
                document.getElementById("movetop").style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
    <!-- /move top -->

    <script src="~/client/js/jquery-3.3.1.min.js"></script> <!-- Common jquery plugin -->

    <script src="~/client/js/theme-change.js"></script><!-- theme switch js (light and dark)-->

    <script src="~/client/js/owl.carousel.js"></script><!-- owl carousel -->
    <!-- script for tesimonials carousel slider -->
    <script>
        $(document).ready(function () {
            $("#owl-demo1").owlCarousel({
                loop: true,
                margin: 20,
                nav: false,
                responsiveClass: true,
                responsive: {
                    0: {
                        items: 1,
                        nav: false
                    },
                    1000: {
                        items: 1,
                        nav: false,
                        loop: false
                    }
                }
            })
        })
    </script>
    <!-- //script for tesimonials carousel slider -->

    <script src="~/client/js/jquery.magnific-popup.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.popup-with-zoom-anim').magnificPopup({
                type: 'inline',

                fixedContentPos: false,
                fixedBgPos: true,

                overflowY: 'auto',

                closeBtnInside: true,
                preloader: false,

                midClick: true,
                removalDelay: 300,
                mainClass: 'my-mfp-zoom-in'
            });

            $('.popup-with-move-anim').magnificPopup({
                type: 'inline',

                fixedContentPos: false,
                fixedBgPos: true,

                overflowY: 'auto',

                closeBtnInside: true,
                preloader: false,

                midClick: true,
                removalDelay: 300,
                mainClass: 'my-mfp-slide-bottom'
            });
        });
    </script>

    <script src="~/client/js/counter.js"></script>

    <!-- gallery popup js -->
    <script src="~/client/js/smartphoto.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const sm = new SmartPhoto(".js-img-viwer", {
                showAnimation: false
            });
            // sm.destroy();
        });
    </script>
    <!-- //gallery popup js -->
    <!--/MENU-JS-->
    <script>
        $(window).on("scroll", function () {
            var scroll = $(window).scrollTop();

            if (scroll >= 80) {
                $("#site-header").addClass("nav-fixed");
            } else {
                $("#site-header").removeClass("nav-fixed");
            }
        });

        //Main navigation Active Class Add Remove
        $(".navbar-toggler").on("click", function () {
            $("header").toggleClass("active");
        });
        $(document).on("ready", function () {
            if ($(window).width() > 991) {
                $("header").removeClass("active");
            }
            $(window).on("resize", function () {
                if ($(window).width() > 991) {
                    $("header").removeClass("active");
                }
            });
        });
    </script>
    <!--//MENU-JS-->
    <!-- disable body scroll which navbar is in active -->
    <script>
        $(function () {
            $('.navbar-toggler').click(function () {
                $('body').toggleClass('noscroll');
            })
        });
    </script>
    <!-- //disable body scroll which navbar is in active -->
    <!--bootstrap-->
    <script src="~/client/js/bootstrap.min.js"></script>
    <!-- //bootstrap-->

</body>

</html>